// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Website.DAL;

namespace Website.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20181203135533_add-eav")]
    partial class addeav
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Website.Common.Models.Daily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AverageEggs");

                    b.Property<DateTime>("Date");

                    b.Property<int>("DeadChickens");

                    b.Property<int>("NormalEggs");

                    b.Property<int>("OtherEggs");

                    b.Property<int>("SaleEggs");

                    b.Property<int>("SecondKindEggs");

                    b.Property<int>("TotalChickens");

                    b.Property<int>("TotalEggs");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.ToTable("Daily");
                });

            modelBuilder.Entity("Website.Common.Models.EAV.Attribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label");

                    b.HasKey("Id");

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("Website.Common.Models.EAV.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttributeId");

                    b.Property<int?>("EntityId");

                    b.Property<int>("Type");

                    b.Property<int?>("ValueId");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.HasIndex("EntityId");

                    b.HasIndex("ValueId");

                    b.ToTable("Values");
                });

            modelBuilder.Entity("Website.Common.Models.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Entities");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Entity");
                });

            modelBuilder.Entity("Website.Common.Models.Page", b =>
                {
                    b.HasBaseType("Website.Common.Models.Entity");

                    b.Property<string>("Url");

                    b.HasIndex("Url");

                    b.ToTable("Page");

                    b.HasDiscriminator().HasValue("Page");
                });

            modelBuilder.Entity("Website.Common.Models.EAV.Value", b =>
                {
                    b.HasOne("Website.Common.Models.EAV.Attribute", "Attribute")
                        .WithMany("Values")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Website.Common.Models.Entity", "Entity")
                        .WithMany("Values")
                        .HasForeignKey("EntityId");

                    b.HasOne("Website.Common.Models.EAV.Value", "Val")
                        .WithMany()
                        .HasForeignKey("ValueId");
                });
#pragma warning restore 612, 618
        }
    }
}
