// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Website.DAL;

namespace Website.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20181203134124_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Website.Common.Models.Daily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AverageEggs");

                    b.Property<DateTime>("Date");

                    b.Property<int>("DeadChickens");

                    b.Property<int>("NormalEggs");

                    b.Property<int>("OtherEggs");

                    b.Property<int>("SaleEggs");

                    b.Property<int>("SecondKindEggs");

                    b.Property<int>("TotalChickens");

                    b.Property<int>("TotalEggs");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.ToTable("Daily");
                });
#pragma warning restore 612, 618
        }
    }
}
