// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Website.DAL;

namespace Website.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Website.Common.Models.Daily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AverageEggs");

                    b.Property<DateTime>("Date");

                    b.Property<int>("DeadChickens");

                    b.Property<int>("NormalEggs");

                    b.Property<int>("OtherEggs");

                    b.Property<int>("SaleEggs");

                    b.Property<int>("SecondKindEggs");

                    b.Property<int>("TotalChickens");

                    b.Property<int>("TotalEggs");

                    b.HasKey("Id");

                    b.ToTable("Daily");
                });

            modelBuilder.Entity("Website.Common.Models.EAV.Attribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("Website.Common.Models.EAV.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttributeId");

                    b.Property<int?>("GroupId");

                    b.Property<int?>("Int");

                    b.Property<string>("SerializedString");

                    b.Property<string>("String");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.HasIndex("GroupId");

                    b.HasIndex("SerializedString");

                    b.ToTable("Values");
                });

            modelBuilder.Entity("Website.Common.Models.EAV.Value", b =>
                {
                    b.HasOne("Website.Common.Models.EAV.Attribute", "Attribute")
                        .WithMany("Values")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Website.Common.Models.EAV.Value", "Group")
                        .WithMany("Values")
                        .HasForeignKey("GroupId");
                });
#pragma warning restore 612, 618
        }
    }
}
